# Generated by Django 3.0.4 on 2020-05-04 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_location', models.SmallIntegerField()),
                ('y_location', models.SmallIntegerField()),
                ('color', models.CharField(max_length=250)),
                ('order', models.SmallIntegerField()),
                ('img_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('User Image', 'User Image'), ('Nature', 'Nature'), ('Food', 'Food'), ('Animal', 'Animal'), ('Sports', 'Sports'), ('Cars', 'Cars'), ('Art', 'Art')], max_length=10)),
                ('image', models.ImageField(upload_to='password_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('age', models.IntegerField()),
                ('pw_user', models.BooleanField()),
                ('remember_pw', models.BooleanField()),
                ('pw_scheme', models.CharField(choices=[('Alphanumeric', 'Alphanumeric'), ('Old Passpoints', 'Old Passpoints'), ('New Passpoints', 'New Passpoints')], max_length=14)),
                ('date_registered', models.DateField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='SusResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now)),
                ('q1', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q2', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q3', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q4', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q5', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q6', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q7', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q8', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q9', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('q10', models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_submit', models.TimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='OldPpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.ClickPoint')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='NewPpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_number', models.SmallIntegerField()),
                ('cp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.ClickPoint')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_login', models.TimeField()),
                ('login_period', models.SmallIntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='CreateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_create', models.TimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmed', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_confirm', models.TimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.CreateModel(
            name='ClickPointFail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_location', models.SmallIntegerField()),
                ('y_location', models.SmallIntegerField()),
                ('color', models.CharField(max_length=250)),
                ('order', models.SmallIntegerField()),
                ('img_number', models.SmallIntegerField()),
                ('date_fail', models.DateTimeField(default=django.utils.timezone.now)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Image')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser')),
            ],
        ),
        migrations.AddField(
            model_name='clickpoint',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Image'),
        ),
        migrations.AddField(
            model_name='clickpoint',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.PasswordUser'),
        ),
    ]
